export const SIMPLE_ACTION = "SIMPLE_ACTION ";
export const LOGIN_ACTION = "LOGIN_ACTION ";
export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
