export const AUTH_ACTION = "AUTH_ACTION";
export const AUTH_ERROR_ACTION = "AUTH_ERROR_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE";
export const FETCH_EVENTS_ACTION = "FETCH_EVENTS_ACTION";
export const EVENTS_FETCH_ERROR_ACTION = "EVENTS_FETCH_ERROR_ACTION";
export const LOAD_EVENTS_ACTION = "LOAD_EVENTS_ACTION";
export const GET_SESSION_AUTHTOKEN_ACTION = "GET_SESSION_AUTHTOKEN_ACTION";
export const NO_SESSION_TOKEN_ACTION = "NO_SESSION_TOKEN_ACTION";




export const SIMPLE_ACTION = "SIMPLE_ACTION ";
export const REQUEST_AUTH_ACTION = "REQUEST_AUTH_ACTION";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
// export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION ";
